-- ======================
-- DROP DAS TABELAS DE RELACIONAMENTO
-- ======================
DROP TABLE IF EXISTS Talhao_Colaborador CASCADE;
DROP TABLE IF EXISTS Talhao_Operacao CASCADE;
DROP TABLE IF EXISTS Talhao_Cultura CASCADE;
DROP TABLE IF EXISTS Leitura_Umidade CASCADE;
DROP TABLE IF EXISTS Leitura_Temperatura CASCADE;
DROP TABLE IF EXISTS Colaborador CASCADE;
DROP TABLE IF EXISTS Talhao CASCADE;
DROP TABLE IF EXISTS Sensor_Umidade CASCADE;
DROP TABLE IF EXISTS Sensor_Temperatura CASCADE;
DROP TABLE IF EXISTS Operacao CASCADE;
DROP TABLE IF EXISTS Cultura CASCADE;
DROP TABLE IF EXISTS Usuario CASCADE;
DROP TABLE IF EXISTS Medida CASCADE;
DROP TABLE IF EXISTS Permissao CASCADE;
